version: 2

jobs:
  test:
    docker:
    - image: circleci/golang:1.12
    working_directory: /go/src/github.com/fstehle/serverless-xray-example
    steps:
    - checkout
    - run: make lint

  build:
    docker:
    - image: circleci/golang:1.12
    working_directory: /go/src/github.com/fstehle/serverless-xray-example
    steps:
    - checkout
    - run: make build

workflows:
  version: 2

  build-and-test:
    jobs:
    - test
    - build